name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.8.0

      - name: Build
        run: zig build
        
      - name: Test
        run: zig build test

      - name: Build artifacts
        run: |
          set -e
          declare -a targets=("x86_64-linux" "x86_64-macos" "aarch64-macos")

          for target in "${targets[@]}"; do
            mkdir -p artifacts/$target
            echo "Building target ${target}..."	    
            zig build -Dtarget=${target} -Drelease-small --prefix artifacts/${target}/
            pushd artifacts/${target}/
            tar cfJ ${target}.tar.xz bin/*
            mv ${target}.tar.xz ../
            popd
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: artifacts/*.tar.xz